import type { Locale } from "../i18n";

const english: Record<string, string> = {
  "概要": "Overview",
  "許可": "Allowed",
  "保留": "On hold",
  "拠点": "Locations",
  "決済": "Payments",
  "契約・ENS": "Leases & ENS",
  "処理": "Operations",
  "監査ログ": "Audit log",
  "販売中": "Available",
  "停止中": "Paused",
  "処理待ち": "Pending",
  "決済確認中": "Confirming payment",
  "照合中": "Reconciling",
  "結果不明": "Unknown outcome",
  "反映確認中": "Awaiting readback",
  "要確認": "Needs review",
  "有効": "Active",
  "期限切れ": "Expired",
  "完了": "Fulfilled",
  "失敗": "Failed",
  "未購入": "Not purchased",
  "同期済み": "Synced",
  "受付済み": "Requested",
  "反映済み": "Applied",
  "拒否": "Rejected",
  "照合要求済み": "Reconciliation queued",
  "公開エリア": "Public area",
  "郵便番号": "Postal code",
  "提供住所": "Service address",
  "販売状態": "Sales status",
  "発行済み契約": "Issued leases",
  "決済ID": "Payment ID",
  "種類": "Kind",
  "拠点ID": "Location ID",
  "仮想区画": "Virtual slot",
  "金額（atomic）": "Amount (atomic)",
  "状態": "Status",
  "リスク判定": "Risk verdict",
  "理由コード": "Reason code",
  "作成日時": "Created at",
  "契約ID": "Lease ID",
  "契約状態": "Lease status",
  "期限": "Expires at",
  "ENS名": "ENS name",
  "ENS種別": "ENS name type",
  "ENS状態": "ENS status",
  "Registry状態": "Registry status",
  "転送設定": "Forwarding setting",
  "転送先登録有無": "Destination configured",
  "処理ID": "Operation ID",
  "種別": "Kind",
  "対象ID": "Target ID",
  "最終エラー": "Last error",
  "次回確認": "Next check",
  "更新日時": "Updated at",
  "日時": "Time",
  "操作": "Action",
  "対象種別": "Target type",
  "結果": "Result",
  "理由": "Reason",
  "変更前": "Before",
  "変更後": "After",
  "無効": "Disabled",
  "登録済み": "Configured",
  "未登録": "Not configured",
  "標準名": "Standard name",
  "custom名": "Custom name",
  "サーバーへ接続できませんでした。接続を確認してください。": "Could not connect to the server. Check your connection.",
  "拠点が別の操作で更新されました。最新値を読み直してください。": "Another operation updated this location. Reload the latest values.",
  "住所契約の料金設定がまだ完了していません。設定完了後に登録してください。": "Address pricing is not configured yet. Register after configuration is complete.",
  "決済・安全性確認の接続準備中のため、販売を再開できません。": "Sales cannot resume until payment and security connections are ready.",
  "読取照合の実行は準備中です。現在の状態は一覧から確認できます。": "Read reconciliation is not ready yet. Check the current status in the list.",
  "ログインの有効期限が切れました。もう一度ログインしてください。": "Your session has expired. Sign in again.",
  "登録済みの運営者アカウントでログインしてください。": "Sign in with a registered operator account.",
  "同じ操作IDに異なる内容が指定されました。対象の状態を再取得してください。": "Different content was submitted with the same operation ID. Reload the target state.",
  "入力内容を確認してください。": "Check the entered values.",
  "この操作を行う権限がありません。": "You do not have permission for this action.",
  "処理を完了できませんでした。内容を確認して再度お試しください。": "Could not complete the operation. Check the details and try again.",
  "監査ログの絞り込みには対象種別と対象IDの両方を入力してください。": "Enter both target type and target ID to filter the audit log.",
  "ID検索は他の絞り込みと併用できません。条件をクリアしてください。": "ID lookup cannot be combined with other filters. Clear the filters.",
  "通信結果を確認できません。新しい操作を作らず、同じ内容・同じ操作IDで再試行するか、対象状態を再取得してください。": "The communication outcome is unknown. Retry the same content and operation ID, or reload the target state before creating another operation.",
  "編集内容を破棄して閉じますか？": "Discard your changes and close?",
  "理由は3文字以上で入力してください。": "Enter a reason with at least 3 characters.",
  "拠点登録": "Location registration",
  "変更された項目はありません。": "No fields have changed.",
  "拠点情報の更新": "Location update",
  "拠点の販売を再開": "Resume location sales",
  "拠点の販売を停止": "Pause location sales",
  "販売再開": "Resume sales",
  "販売停止": "Pause sales",
  "読取照合を要求": "Request read reconciliation",
  "読取照合要求": "Read reconciliation request",
  "運用者認証を確認しています": "Checking operator authentication",
  "管理APIへ接続しています。": "Connecting to the admin API.",
  "運用者ログイン": "Operator sign-in",
  "管理画面は未設定です": "Admin console is not configured",
  "管理画面へ接続できません": "Could not connect to the admin console",
  "運用者データを表示するには、登録済みアカウントでログインしてください。": "Sign in with a registered account to view operator data.",
  "運用者認証が設定されていないため、管理データは表示できません。": "Operator authentication is not configured, so admin data cannot be displayed.",
  "Googleでログイン": "Sign in with Google",
  "再試行": "Try again",
  "公開トップへ": "Public home",
  "運用メニュー": "Operator navigation",
  "運用コンソール": "Operator console",
  "更新": "Refresh",
  "ログアウト": "Sign out",
  "結果不明の操作があります。": "An operation has an unknown outcome.",
  "同じ操作を再試行": "Retry the same operation",
  "拠点を登録": "Register location",
  "データを読み込んでいます。": "Loading data.",
  "前へ": "Previous",
  "次へ": "Next",
  "操作理由": "Reason for action",
  "理由は監査記録に保存されます。3〜500文字で入力してください。": "The reason is saved in the audit log. Enter 3–500 characters.",
  "キャンセル": "Cancel",
  "実行": "Execute",
  "概要を取得できません。更新してください。": "Could not load the overview. Refresh to try again.",
  "有効契約": "Active leases",
  "同期保留": "Sync pending",
  "集計を取得できません。未取得を0件として表示していません。": "Metrics are unavailable. Missing values are not shown as zero.",
  "取得不可": "Unavailable",
  "処理の確認": "Review operations",
  "すべて": "All",
  "決済状態": "Payment status",
  "処理種別": "Operation kind",
  "IDで一件検索": "Look up one record by ID",
  "検索": "Search",
  "条件クリア": "Clear filters",
  "ID検索は他条件・ページ送りと併用しません。": "ID lookup does not use other filters or pagination.",
  "表示するデータがありません": "No data to display",
  "絞り込み条件を確認するか、必要な運用操作を行ってください。": "Check the filters or perform the required operator action.",
  "詳細 / 操作": "Details / Actions",
  "詳細": "Details",
  "編集": "Edit",
  "停止": "Pause",
  "再開": "Resume",
  "照合要求": "Request reconciliation",
  "閉じる": "Close",
  "表示名": "Display name",
  "変更理由": "Reason for change",
  "30日固定plan: testnet/dev 0.55 USDC。新規拠点は停止状態で登録され、販売再開は別操作です。": "Fixed 30-day plan: testnet/dev 0.55 USDC. New locations are registered as paused. Resuming sales is a separate action.",
  "停止状態で登録": "Register as paused",
  "拠点を編集": "Edit location",
  "変更を保存": "Save changes"
};

export function adminCopy(locale: Locale, text: string): string {
  if (locale === "ja") return text;
  if (english[text]) return english[text];
  let match = text.match(/^(.+)を送信しています。$/s);
  if (match) return `Sending ${adminCopy(locale, match[1]!)}.`;
  match = text.match(/^(.+)を受け付けました。状態を更新します。$/s);
  if (match) return `${adminCopy(locale, match[1]!)} was accepted. Refreshing the status.`;
  match = text.match(/^「(.*)」を販売中にします。提供住所を利用・公開する許可を確認し、理由を入力してください。$/s);
  if (match) return `Enable sales for “${match[1]}”. Confirm permission to use and publish the service address, then enter a reason.`;
  match = text.match(/^「(.*)」の新規販売を停止します。成立済み契約や既存照合は変更しません。理由を入力してください。$/s);
  if (match) return `Pause new sales for “${match[1]}”. Existing leases and reconciliation remain unchanged. Enter a reason.`;
  match = text.match(/^処理 (.*) の既存決済・chain状態を読み取り再確認します。送金、契約の強制反映、chain書込は行いません。$/s);
  if (match) return `Read and recheck existing payment and chain state for operation ${match[1]}. This does not transfer funds, force a lease update, or write to the chain.`;
  return text;
}
