import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import { Firestore } from '@google-cloud/firestore';
import { DomainError, newOpaqueToken, sha256 } from '@realaddr/domain';
import { OwnerReadRepository, WorldRepository, type AgentPrincipal, type WorldEnvelope } from '../src/index.js';
const encrypted: WorldEnvelope = { algorithm: 'aes-256-gcm', keyId: 'test-key', iv: Buffer.alloc(12).toString('base64'), ciphertext: Buffer.from('private').toString('base64'), tag: Buffer.alloc(16).toString('base64') };
const rejected = (e: unknown) => e instanceof DomainError;
test('applied destination write approval permits fresh login after session expiry until its snapshot changes', { skip: !process.env.FIRESTORE_EMULATOR_HOST }, async () => {
  const db = new Firestore({ projectId: `demo-realaddr-${randomUUID()}`, databaseId: 'realaddr' });
  try {
    let now = new Date('2026-09-26T00:00:00Z');
    const repo = new WorldRepository(db, 'realaddr_event_', { now: () => now });
    const id = randomUUID(), consentId = randomUUID();
    const p: AgentPrincipal = { tenantId: randomUUID(), agentId: randomUUID(), walletAddress: `0x${'a'.repeat(40)}`, walletChain: 'eip155:84532', credentialId: randomUUID() };
    const order = { schemaVersion: 1, id, tenantId: p.tenantId, agentId: p.agentId, ownerWallet: p.walletAddress, kind: 'purchase', status: 'fulfilled', leaseId: id, network: 'eip155:84532', asset: `0x${'1'.repeat(40)}`, payTo: `0x${'2'.repeat(40)}`, amountAtomic: '550000' };
    const payment = { schemaVersion: 1, id, orderId: id, status: 'confirmed', network: order.network, asset: order.asset, payTo: order.payTo, payer: p.walletAddress, amountAtomic: order.amountAtomic, txHash: `0x${'3'.repeat(64)}`, transferLogIndex: 0, evidenceHash: 'b'.repeat(64), settlementEvidence: { finalityVerified: true, evidenceHash: 'b'.repeat(64) } };
    await repo.collections.doc('orders', id).set(order);
    await repo.collections.doc('payments', id).set(payment);
    await repo.collections.doc('uniques', sha256(JSON.stringify(['payment_transfer', payment.network, payment.txHash, '0']))).set({ kind: 'payment_transfer', orderId: id, paymentId: id });
    await repo.collections.doc('leases', id).set({ schemaVersion: 1, id, tenantId: p.tenantId, agentId: p.agentId, ownerWallet: p.walletAddress, status: 'active', registryPaymentOrderId: id, version: 1, expiresAt: new Date(now.getTime() + 86400000) });
    await repo.collections.doc('human_bindings', id).set({ schemaVersion: 1, leaseId: id, ownerWallet: p.walletAddress, keyedSubjectHash: 'a'.repeat(64) });
    await repo.collections.doc('approvals', consentId).set({ schemaVersion: 1, id: consentId, leaseId: id, tenantId: p.tenantId, agentId: p.agentId, ownerWallet: p.walletAddress, leaseVersion: 1, policyVersion: 'mail-v1', status: 'applied', keyedSubjectHash: 'a'.repeat(64), targetProfileVersion: 1, targetDestinationVersion: 1, expiresAt: now, actionHash: 'a'.repeat(64) });
    await repo.collections.doc('mail_profiles', id).set({ schemaVersion: 1, leaseId: id, status: 'enabled', version: 2, destinationVersion: 1, destinationConfigured: true, encryptedDestination: encrypted, ownerWallet: p.walletAddress, policyVersion: 'mail-v1', enabledByApprovalId: consentId, approvedDestinationVersion: 1, initialDestinationPending: false });
    const login = async (approvalId: string) => {
      const s = await repo.createBrowserSession(approvalId);
      const c = await repo.issueOwnerChallenge(approvalId, s.token, s.csrfToken, { domain: 'localhost', chain: p.walletChain });
      await repo.consumeOwnerProof(approvalId, s.token, s.csrfToken, { verified: true, challengeId: c.id, walletAddress: p.walletAddress, chain: p.walletChain, domain: 'localhost', message: c.message });
      const state = newOpaqueToken();
      const o = await repo.beginOidc(approvalId, s.token, s.csrfToken, { state, nonce: newOpaqueToken(), encryptedPkceVerifier: encrypted });
      await repo.claimOidc(state, s.token);
      await repo.finishOidc(o.id, s.token, { verified: true, issuer: 'test-issuer', subject: 'test-subject', keyedSubjectHash: 'a'.repeat(64), encryptedIssuer: encrypted, encryptedSubject: encrypted, authTime: now });
      return s;
    };
    const initial = await login(consentId);
    const change = await repo.createDestinationApproval(id, initial.token, initial.csrfToken, { expectedVersion: 2, policyVersion: 'mail-v1' });
    const approved = await login(change.id);
    await repo.decide(change.id, approved.token, approved.csrfToken, { decision: 'approve', actionHash: change.actionHash });
    now = new Date(now.getTime() + 600001);
    await assert.rejects(repo.getApproval(change.id, approved.token), rejected);
    const fresh = await login(change.id);
    assert.equal((await repo.getMailProfile(id, fresh.token)).destinationVersion, 1);
    const saved = await repo.saveDestination(id, fresh.token, fresh.csrfToken, { expectedVersion: 2, encryptedDestination: encrypted });
    assert.equal(saved.destinationVersion, 2);
    assert.equal(saved.version, 3);
    const next = await repo.createDestinationApproval(id, fresh.token, fresh.csrfToken, { expectedVersion: 3, policyVersion: 'mail-v1' });
    const ns = await login(next.id);
    await repo.decide(next.id, ns.token, ns.csrfToken, { decision: 'approve', actionHash: next.actionHash });
    await repo.collections.doc('leases', id).update({ version: 2 });
    await assert.rejects(login(next.id), rejected);
    await repo.collections.doc('leases', id).update({ version: 1 });
    await repo.collections.doc('approvals', next.id).update({ targetDestinationVersion: 4 });
    await assert.rejects(login(next.id), rejected);
  }
  finally {
    await db.terminate();
  }
});
test('World owner/session/OIDC/consent and one-time address writes are atomic and private', { skip: !process.env.FIRESTORE_EMULATOR_HOST }, async () => {
  const db = new Firestore({ projectId: `demo-realaddr-${randomUUID()}`, databaseId: 'realaddr' });
  try {
    let now = new Date('2026-09-26T00:00:00Z');
    const repo = new WorldRepository(db, 'realaddr_event_', { now: () => now });
    const owner = new OwnerReadRepository(db, 'realaddr_event_', { now: () => now });
    const id = randomUUID(), buildingId = randomUUID();
    const p: AgentPrincipal = { tenantId: randomUUID(), agentId: randomUUID(), walletAddress: `0x${'a'.repeat(40)}`, walletChain: 'eip155:84532', credentialId: randomUUID() };
    const receiptId = id;
    const order = { schemaVersion: 1, id, tenantId: p.tenantId, agentId: p.agentId, ownerWallet: p.walletAddress, kind: 'purchase', status: 'fulfilled', leaseId: id, network: 'eip155:84532', asset: `0x${'1'.repeat(40)}`, payTo: `0x${'2'.repeat(40)}`, amountAtomic: '550000' };
    const payment = { schemaVersion: 1, id, orderId: id, status: 'confirmed', network: order.network, asset: order.asset, payTo: order.payTo, payer: p.walletAddress, amountAtomic: order.amountAtomic, txHash: `0x${'3'.repeat(64)}`, transferLogIndex: 0, evidenceHash: 'b'.repeat(64), settlementEvidence: { finalityVerified: true, evidenceHash: 'b'.repeat(64) } };
    await repo.collections.doc('orders', id).set(order);
    await repo.collections.doc('payments', id).set(payment);
    await repo.collections.doc('uniques', sha256(JSON.stringify(['payment_transfer', payment.network, payment.txHash, '0']))).set({ schemaVersion: 1, kind: 'payment_transfer', orderId: id, paymentId: id });
    await repo.collections.doc('leases', id).set({ schemaVersion: 1, id, tenantId: p.tenantId, agentId: p.agentId, ownerWallet: p.walletAddress, status: 'active', registryPaymentOrderId: receiptId, version: 1, startsAt: now, expiresAt: new Date(now.getTime() + 86400000), buildingId, slotNumber: 42, addressSnapshot: { postalCode: '1000001', address: 'Test address' }, chainSyncStatus: 'pending', updatedAt: now });
    await repo.collections.doc('mail_profiles', id).set({ schemaVersion: 1, leaseId: id, status: 'disabled', version: 1, destinationConfigured: false, encryptedDestination: null });
    const [a, a2] = await Promise.all([repo.createApproval(p, id, { idempotencyKey: 'world-test-1', policyVersion: 'mail-v1' }), repo.createApproval(p, id, { idempotencyKey: 'world-test-1', policyVersion: 'mail-v1' })]);
    assert.equal(a.id, a2.id);
    const session = await repo.createBrowserSession(a.id);
    assert.equal(JSON.stringify((await repo.collections.doc('browser_sessions', sha256(session.token)).get()).data()).includes(session.token), false);
    await assert.rejects(repo.getApproval(a.id, session.token), rejected);
    await assert.rejects(repo.issueOwnerChallenge(a.id, session.token, 'bad', { domain: 'localhost', chain: p.walletChain }), rejected);
    const prove = async (approvalId: string, s: typeof session) => {
      const c = await repo.issueOwnerChallenge(approvalId, s.token, s.csrfToken, { domain: 'localhost', chain: p.walletChain });
      await assert.rejects(repo.consumeOwnerProof(approvalId, s.token, s.csrfToken, { verified: true, challengeId: c.id, walletAddress: `0x${'c'.repeat(40)}`, chain: p.walletChain, domain: 'localhost', message: c.message }), rejected);
      await repo.consumeOwnerProof(approvalId, s.token, s.csrfToken, { verified: true, challengeId: c.id, walletAddress: p.walletAddress, chain: p.walletChain, domain: 'localhost', message: c.message });
      await assert.rejects(repo.consumeOwnerProof(approvalId, s.token, s.csrfToken, { verified: true, challengeId: c.id, walletAddress: p.walletAddress, chain: p.walletChain, domain: 'localhost', message: c.message }), rejected);
    };
    const authenticate = async (approvalId: string, s: typeof session, subject = 'a'.repeat(64)) => {
      const state = newOpaqueToken(), nonce = newOpaqueToken();
      const attempt = await repo.beginOidc(approvalId, s.token, s.csrfToken, { state, nonce, encryptedPkceVerifier: encrypted });
      const claims = await Promise.allSettled([repo.claimOidc(state, s.token), repo.claimOidc(state, s.token)]);
      assert.equal(claims.filter(x => x.status === 'fulfilled').length, 1);
      await repo.finishOidc(attempt.id, s.token, { verified: true, issuer: 'test-issuer', subject: 'test-subject', keyedSubjectHash: subject, encryptedIssuer: encrypted, encryptedSubject: encrypted, authTime: now });
    };
    await prove(a.id, session);
    await authenticate(a.id, session);
    assert.equal((await repo.collections.doc('mail_profiles', id).get()).data()?.status, 'disabled');
    assert.equal((await repo.collections.doc('human_bindings', id).get()).exists, false);
    await assert.rejects(repo.decide(a.id, session.token, 'bad', { decision: 'approve', actionHash: a.actionHash }), rejected);
    const applied = await repo.decide(a.id, session.token, session.csrfToken, { decision: 'approve', actionHash: a.actionHash });
    assert.equal(applied.status, 'enabled');
    assert.equal(applied.destinationConfigured, false);
    assert.deepEqual(await repo.decide(a.id, session.token, session.csrfToken, { decision: 'approve', actionHash: a.actionHash }), applied);
    await repo.saveDestination(id, session.token, session.csrfToken, { expectedVersion: 1, encryptedDestination: encrypted });
    await assert.rejects(repo.saveDestination(id, session.token, session.csrfToken, { expectedVersion: 2, encryptedDestination: encrypted }), rejected);
    assert.deepEqual((await repo.getMailProfile(id, session.token)).encryptedDestination, encrypted);
    const dto = await owner.getSubscription(p, id);
    assert.equal(dto.mail.status, 'enabled');
    assert.ok(!JSON.stringify(dto).includes('private'));
    const reuse = await repo.createApproval(p, id, { idempotencyKey: 'world-login', policyVersion: 'mail-v1', forceReauth: true });
    assert.equal(reuse.id, a.id);
    const change = await repo.createDestinationApproval(id, session.token, session.csrfToken, { expectedVersion: 2, policyVersion: 'mail-v1' });
    const changedSession = await repo.createBrowserSession(change.id);
    await prove(change.id, changedSession);
    await authenticate(change.id, changedSession);
    await repo.decide(change.id, changedSession.token, changedSession.csrfToken, { decision: 'approve', actionHash: change.actionHash });
    assert.equal((await repo.getMailProfile(id, session.token)).version, 2);
    await repo.disableMail(id, session.token, session.csrfToken, { expectedVersion: 2 });
    await assert.rejects(repo.saveDestination(id, changedSession.token, changedSession.csrfToken, { expectedVersion: 3, encryptedDestination: encrypted }), rejected);
    assert.equal((await repo.getMailProfile(id, session.token)).encryptedDestination, null);
    await repo.collections.doc('leases', id).update({ version: 2, expiresAt: new Date(now.getTime() + 86400000) });
    assert.equal((await owner.getSubscription(p, id)).mail.status, 'disabled');
    const reen = await repo.createApproval(p, id, { idempotencyKey: 'world-reenable', policyVersion: 'mail-v1' });
    const rs = await repo.createBrowserSession(reen.id);
    await prove(reen.id, rs);
    await authenticate(reen.id, rs);
    await repo.decide(reen.id, rs.token, rs.csrfToken, { decision: 'approve', actionHash: reen.actionHash });
    assert.equal((await repo.getMailProfile(id, rs.token)).status, 'enabled');
    await repo.collections.doc('leases', id).update({ expiresAt: now });
    assert.equal((await owner.getSubscription(p, id)).mail.status, 'suspended');
    assert.equal((await repo.getMailProfile(id, rs.token)).encryptedDestination, null);
    await repo.collections.doc('leases', id).update({ version: 3, expiresAt: new Date(now.getTime() + 86400000) });
    assert.equal((await owner.getSubscription(p, id)).mail.status, 'enabled');
    assert.equal((await repo.collections.doc('approvals', reen.id).get()).data()?.status, 'applied');
    const stale = await repo.createDestinationApproval(id, rs.token, rs.csrfToken, { expectedVersion: 3, policyVersion: 'mail-v1' });
    await repo.collections.doc('approvals', stale.id).update({ targetDestinationVersion: 1 });
    const matching = await repo.createDestinationApproval(id, rs.token, rs.csrfToken, { expectedVersion: 3, policyVersion: 'mail-v1' });
    assert.notEqual(matching.id, stale.id);
    await repo.collections.doc('approvals', matching.id).update({ policyVersion: 'old-policy' });
    const current = await repo.createDestinationApproval(id, rs.token, rs.csrfToken, { expectedVersion: 3, policyVersion: 'mail-v1' });
    assert.notEqual(current.id, matching.id);
    const staleSession = await repo.createBrowserSession(current.id);
    await prove(current.id, staleSession);
    const state = newOpaqueToken(), finishState = newOpaqueToken();
    await repo.beginOidc(current.id, staleSession.token, staleSession.csrfToken, { state, nonce: newOpaqueToken(), encryptedPkceVerifier: encrypted });
    const finishAttempt = await repo.beginOidc(current.id, staleSession.token, staleSession.csrfToken, { state: finishState, nonce: newOpaqueToken(), encryptedPkceVerifier: encrypted });
    await repo.claimOidc(finishState, staleSession.token);
    await repo.collections.doc('leases', id).update({ version: 4 });
    await assert.rejects(repo.beginOidc(current.id, staleSession.token, staleSession.csrfToken, { state: newOpaqueToken(), nonce: newOpaqueToken(), encryptedPkceVerifier: encrypted }), rejected);
    await assert.rejects(repo.claimOidc(state, staleSession.token), rejected);
    await assert.rejects(repo.finishOidc(finishAttempt.id, staleSession.token, { verified: true, issuer: 'test-issuer', subject: 'test-subject', keyedSubjectHash: 'a'.repeat(64), encryptedIssuer: encrypted, encryptedSubject: encrypted, authTime: now }), rejected);
    assert.equal((await repo.collections.doc('browser_sessions', sha256(staleSession.token)).get()).data()?.keyedSubjectHash, undefined);
    await assert.rejects(repo.decide(current.id, staleSession.token, staleSession.csrfToken, { decision: 'approve', actionHash: current.actionHash }), rejected);
    const wrong = await repo.createBrowserSession(reen.id);
    await prove(reen.id, wrong);
    await assert.rejects(authenticate(reen.id, wrong, 'c'.repeat(64)), rejected);
    now = new Date(now.getTime() + 600001);
    const login = await repo.createBrowserSession(reen.id);
    await prove(reen.id, login);
    await authenticate(reen.id, login);
    assert.equal((await repo.getMailProfile(id, login.token)).status, 'enabled');
    const rotated = await repo.rotateSession(login.token);
    assert.equal(rotated.expiresAt, login.expiresAt);
    assert.notEqual(rotated.token, login.token);
    assert.notEqual(rotated.csrfToken, login.csrfToken);
    await assert.rejects(repo.getMailProfile(id, login.token), rejected);
    assert.equal((await repo.getMailProfile(id, rotated.token)).status, 'enabled');
    await assert.rejects(repo.disableMail(id, rotated.token, login.csrfToken, { expectedVersion: 3 }), rejected);
    const expired = await repo.createDestinationApproval(id, rotated.token, rotated.csrfToken, { expectedVersion: 3, policyVersion: 'mail-v1' });
    const expiredSession = await repo.createBrowserSession(expired.id);
    await prove(expired.id, expiredSession);
    await repo.collections.doc('approvals', expired.id).update({ expiresAt: now });
    await assert.rejects(repo.beginOidc(expired.id, expiredSession.token, expiredSession.csrfToken, { state: newOpaqueToken(), nonce: newOpaqueToken(), encryptedPkceVerifier: encrypted }), rejected);
    await repo.collections.doc('payments', id).update({ status: 'unknown' });
    await assert.rejects(owner.getSubscription(p, id), rejected);
    now = new Date(now.getTime() + 600001);
    await assert.rejects(repo.getMailProfile(id, rs.token), rejected);
  }
  finally {
    await db.terminate();
  }
});
